name: Exercise
# on issues created or updated
on:
  issues:
    types:
      - opened
      - edited

permissions:
  issues: write
  contents: read

jobs:
  ex1:
    runs-on: ubuntu-latest
    # if issue title is ex1
    if: ${{ github.event.issue.title == 'Ex1' || github.event.issue.title == 'ex1' || github.event.issue.title == '练习1' || github.event.issue.title == '练习一' }}
    steps:
      - uses: actions/checkout@v3
      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body-file: .github/ISSUE_TEMPLATE/exercise1.md
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add label
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['exercise1']
            })
      - name: Assign issue
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ['${{ github.event.issue.user.login }}']
            })

  ex2:
    runs-on: ubuntu-latest
    # if issue title is ex2
    if: ${{ github.event.issue.title == 'Ex2' || github.event.issue.title == 'ex2' || github.event.issue.title == '练习2' || github.event.issue.title == '练习二' }}
    steps:
      - uses: actions/checkout@v3
      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body-file: .github/ISSUE_TEMPLATE/exercise1.md
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add label
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['exercise2']
            })
      - name: Assign issue
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ['${{ github.event.issue.user.login }}']
            })
